name: Build Custom NimBLE Firmware

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-nrf52-fuzzer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Mynewt
      run: |
        sudo apt-get install -y git make gcc-arm-none-eabi python3
        pip3 install --user mynewt
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Apply NimBLE Modifications
      run: |
        # Apply controller patches
        patch -p1 -d repos/apache-mynewt-nimble < patches/controller.patch
        
        # Apply host patches
        patch -p1 -d repos/apache-mynewt-nimble < patches/host.patch
        
        # Apply HCI vendor commands
        patch -p1 -d repos/apache-mynewt-nimble < patches/hci_vendor.patch

    - name: Build Firmware
      run: |
        newt target create nrf52_fuzzer
        newt target set nrf52_fuzzer app=@apache-mynewt-nimble/apps/blehci
        newt target set nrf52_fuzzer bsp=@apache-mynewt-core/hw/bsp/nrf52dk
        newt target set nrf52_fuzzer build_profile=debug
        newt build nrf52_fuzzer
        newt create-image nrf52_fuzzer 1.0.0
        newt obj dump nrf52_fuzzer bin/bleninja.elf > bleninja.elf

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fuzzer-firmware
        path: bleninja.elf
