name: Build BLE Fuzzer Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly builds

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
        sudo apt-get install -y wget git make unzip

    - name: Install and Build Newt
      run: |
        # Clone newt repository
        git clone https://github.com/apache/mynewt-newt.git
        cd mynewt-newt
        # Build newt
        ./build.sh
        # Install newt
        sudo mv newt/newt /usr/local/bin
        cd ..
        # Verify installation
        which newt
        newt version

    - name: Cache newt dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.newt
          project.state
        key: ${{ runner.os }}-newt-${{ hashFiles('project.yml') }}
        restore-keys: |
          ${{ runner.os }}-newt-

    - name: Run Build Script
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
      
    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: ble-fuzzer-firmware
        path: |
          bin/targets/nrf52_bsp/app/*.hex
          bin/targets/nrf52_bsp/app/*.elf
