name: Build Custom NimBLE Firmware

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-nrf52-fuzzer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git make gcc-arm-none-eabi python3 python3-pip golang-go
        # Install Mynewt Newt from source
        wget https://github.com/apache/mynewt-newt/archive/refs/tags/mynewt_1_13_0_tag.zip
        unzip mynewt_1_13_0_tag.zip
        cd mynewt-newt-mynewt_1_13_0_tag
        ./build.sh
        sudo mv newt/newt /usr/local/bin
        newt version
        cd ..

    - name: Initialize Mynewt Core
      run: |
        newt install -f -v apache-mynewt-core

    - name: Checkout NimBLE
      uses: actions/checkout@v4
      with:
        repository: apache/mynewt-nimble
        path: mynewt-nimble

    - name: Add Fuzzing Source code
      run: |
        cp -r mynewt-nimble/nimble/controller/* mynewt-nimble/nimble/controller/
        cp -r mynewt-nimble/nimble/transport/* mynewt-nimble/nimble/transport/
        cp -r mynewt-nimble/nimble/porting/nrf5x mynewt-nimble/nimble/porting/

    - name: Build Fuzzing Firmware
      run: |
        newt target create nrf52_fuzzer
        newt target set nrf52_fuzzer app=@apache-mynewt-nimble/apps/blehci
        newt target set nrf52_fuzzer bsp=@apache-mynewt-core/hw/bsp/nrf52dk
        newt target set nrf52_fuzzer build_profile=optimized
        newt target set nrf52_fuzzer syscfg=BLE_LL_FUZZ_NRF52=1:BLE_PHY_DIRECT_TX=1
        newt build nrf52_fuzzer
        newt create-image nrf52_fuzzer 1.0.0
        newt obj copy nrf52_fuzzer firmware.elf

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ble-fuzzer-firmware
        path: |
          firmware.elf
          repos/apache-mynewt-nimble/bin/nrf52_fuzzer/*
